C ABUILD-	BUILD DUMMY AINDX.DAT FILE FOR ADVENTURE
C
	PROGRAM ABUILD
	IMPLICIT INTEGER(A-Z)
	COMMON /VERSN/ VMAJ,VMIN,VEDIT
	DATA VMAJ/0/,VMIN/0/,VEDIT/0/
C
	CALL SAVEGM(.FALSE.,I)
	CALL EXIT
	END
