#!/usr/bin/perl
# The serial port is too slow to keep up with data at 1200 baud
# when use with COPY TT: FILE.TXT so this program feeds the data
# at a slower speed.
#
# The data must be ASCII-clean and have \r characters.
# \n will be stripped.
#
use warnings;
use strict;
use Time::HiRes 'usleep';

# Slurp in the file
undef $/;
my $data = <>;

# No buffering on output
$|++;

my $baud = 450;

my $len = length $data;
my $count = 0;

printf STDERR "%d bytes: %d:%02d\n",
	$len,
	($len / ($baud / 8)) / 60,
	($len / ($baud / 8)) % 60,
	;

for(my $off=0; $off < $len ; $off++)
{
	# give it a rest each block
	if ($count == 512)
	{
		$count = 0;
		printf STDERR "%d/%d: %d remaining\n",
			$off,
			$len,
			($len - $off) / ($baud / 8),
			;
		usleep 250000;
	}

	my $c = substr($data, $off, 1);
	next if ord($c) == 0x0A;
	print $c;
	usleep 1000000 / ($baud/8);
	$count++;
}
